### ISSUE TITLE
[CONTRACTS] - DebtCouponManager V2 

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#114]
Right now the DebtCouponManager works with uAR but without taking into consideration the DebtClock

## Current features

- Mints claimable dollars to get the price back to 1
- Exchange uAD for uAR 1-1 + premium when TWAP < 1
	-  Premium is calculated by UARForDollarsCalculator
- Exhange uAD for uDEBT + premium when TWAP < 1
	- Premium is calculated by CouponsForDollarsCalculator
- Exchange uAR for uAD 1-1 when TWAP > 1
- Exchange uDEBT for uAD 1-1 when TWAP > 1 and there are more uAD available than uAR
- Exchange expired uDEBT for UBQ at a configurable rate
- Exchange un-expired uDEBT for uAR at same value

## Considerations

At the moment will redeem your uAR fo uAD at 1-1; so if we implement the ubiquity/ubiquity-dollar-development#115  contract and for the [[Proxy Yield Aggregator, we'll need to re-deploy this one to also use it. However, while we keep the inflation at 0% nothing will change. This way we can deploy the YieldProxy contract with the DebtClock while keeping inflation at 0%, and when we also deploy the new DebtCouponManager we can start increasing the rate. Otherwise there is an opportunity to exploit the rate difference between the DebtCouponManager and the YieldProxy. (YieldProxy would give you more uAR to account for inflation, and the DebtCouponManager would redeem them 1-1 instead of inflation-adjusted)

## Sub-tasks

- [ ] ubiquity/ubiquity-dollar-development#112
- [ ] ubiquity/ubiquity-dollar-development#111
- [ ] ubiquity/ubiquity-dollar-development#110
- [ ] ubiquity/ubiquity-dollar-development#109
- [ ] ubiquity/ubiquity-dollar-development#108
- [ ] ubiquity/ubiquity-dollar-development#107
- [x] ubiquity/ubiquity-dollar-development#104
- [ ] Deploy DebtCouponManager V2
- [ ] Revoke previous contract minting permissions

**Comment by 0x4007** [comment]
Consolidated into https://github.com/ubiquity/ubiquity-dollar/issues/115
