### ISSUE TITLE
Yield aggregator UI

### ISSUE THREAD

**Issue by Zequez** [ubiquity/uad-ui#13]
Branch with the new contracts [uad-contracts:proxy-yield-aggregator](https://github.com/ubiquity/uad-contracts/tree/feat/proxy-yield-aggregator)

## Sub-tasks

- [x] Kickstart branch and files https://github.com/ubiquity-vercel/uad-ui/issues/15
- [x] Create final wireframe for the UI 
- [x] Create component with static design https://github.com/ubiquity-vercel/uad-ui/issues/18
- [x] Determine APY calculation based on this ubiquity/ubiquity-dollar-development#119
- [x] Study [uad-contracts:proxy-yield-aggregator](https://github.com/ubiquity/uad-contracts/tree/feat/proxy-yield-aggregator) and lay out all possible interaction and information points
- [x] Either make a task to deploy the contract locally ~~or wait until the contract is deployed on mainnet~~ https://github.com/ubiquity/uad-contracts/pull/54
- [x] Instantiate YieldProxy on the components context
- [x] Load `depositFee`, `maxUbq`, `maxUad`, ` maxYieldMultiplier` and max amounts from ProxyYield contract
- [x] Hook in the contract `deposit` method
- [x] Load deposit information from YieldProxy
- [x] Make component parametric https://github.com/ubiquity-vercel/uad-ui/issues/20
- [x] Add interactivity to uAD input https://github.com/ubiquity-vercel/uad-ui/issues/22
- [x] Add interactivity to UBQ input https://github.com/ubiquity-vercel/uad-ui/issues/21
- [x] Add inputs validations https://github.com/ubiquity-vercel/uad-ui/issues/23
- [x] Loading indicator 
- [x] Withdraw screen wireframe
   <img width="300" alt="Withdraw wireframe" src="https://user-images.githubusercontent.com/126037/136118847-95b9c4df-e890-4666-95aa-54abc66aba66.png">
- [x] Execute transactions on the contracts from the UI inputs
- [x] Hook in the contract `withdrawAll` method
- [x] Disabled states during transactions
- [x] Load balances of `uAD`, `UBQ` and `USDC` tokens respectively https://github.com/ubiquity-vercel/uad-ui/issues/28
- [ ] Load TVL from contracts https://github.com/ubiquity-vercel/uad-ui/issues/27
- [x] Use YieldProxy contract address from Mainnet https://github.com/ubiquity-vercel/uad-ui/issues/33
- [ ] Load real `usdcApy` information from PickleFinance https://github.com/ubiquity-vercel/uad-ui/issues/32
- [x] https://github.com/ubiquity-vercel/uad-ui/issues/37

**Comment by 0x4007** [comment]
![image](https://user-images.githubusercontent.com/4975670/149573655-86c2951c-da29-4618-b6e9-4bb37ee1a3ae.png)


Me messaging @marcomow 

It's a lower priority thing but theres too much info on here currently
<img width="428" alt="Screen Shot 2022-01-14 at 13 25 33" src="https://user-images.githubusercontent.com/4975670/149573550-2a0c3793-e506-44de-b4ef-18a6770bf956.png">

**Comment by Zequez** [comment]
Since the product was already shipped let's close this issue and move the discussion about improvements somewhere else.
We can think about a UI that shows all that info in a more visual, simpler and coherent way.

I created an issue specifically for this: https://github.com/ubiquity/uad-ui/issues/86
